version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: yarn
      - run: yarn prepare
      - run: yarn test --coverage --watchAll=false
      - codecov/upload:
          file: coverage/*.json
      - run: cd example
      - run: yarn
      - run: yarn lint
      - run: cd docs
      - run: yarn
      - run: yarn lint
